config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/home", to: "pages#home"
  
  #get "/recipes", to: "recipes#index"
  #get "/recipes/new", to: "recipes#new", as: "new_recipe"
  #post "/recipes", to: "recipes#create"
  #get "/recipes/:id/edit", to: "recipes#edit", as: "edit_recipe"
  #patch "/recipes/:id", to: "recipes#update"
  #get "/recipes/:id", to: "recipes#show", as: "recipe"
  #delete "/recipes/:id", to: "recipes#destroy"
  
  # rails generate the generic form described earlier
  resources :recipes, except: [:destroy] do
    member do
      post 'like'
    end
  end
  
  delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :chefs, except: [:new] do
    member do
      post 'like'
    end
  end
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [ :new, :create, :show ]
  resources :ingredients, only: [ :new, :create, :show ]
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Should be less than 5MB.")
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :destroy, :like] #kinda weird...
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  
  def index
    #@recipes = Recipe.all.sort_by{|likes| likes.thumbs_up_total}.reverse
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end
  
  def show
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    
    @recipe.chef = current_user

    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Your recipe was deleted successfully!"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    
    if like.valid?
      flash[:success] = "Your selection was successful!"
      redirect_to :back
    else
      flash[:danger] = "You can only like or dislike a recipe once!"
      redirect_to :back
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    
    def require_same_user
      if current_user != @recipe.chef and !current_user.admin?
        flash[:danger] = "You can only edit your own recipes"
        redirect_to recipes_path
      end
    end
    
    def admin_user
      redirect_to recipes_path unless current_user.admin?
    end
end

app/views/recipes/_form.html.erb
<%= render "shared/errors", obj: @recipe %>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :summary %><br>
        <%= f.text_area :summary %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, rows: 10 %>
      </p>
      <p>
        <strong>Styles:</strong>
        <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </p>
      <p>
        <strong>Ingredients:</strong>
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </p>
      <p>
        <span class="picture"><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></span>
      </p>
      <p>
        <%= f.submit(@recipe.new_record? ? "Create Recipe":"Update Recipe", class: "btn btn-success") %>
      </p>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function () {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Recipe' %>
<%= render 'form' %>
<%= link_to 'Return to recipe without saving', recipe_path(@recipe), class: "btn btn-warning" %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'All Recipes' %>

<ul class="nav nav-tabs">
  <li class="active"><%= link_to "Recipes", recipes_path %></li>
  <li><%= link_to "Chefs", chefs_path %></li>
</ul>

<% if logged_in? %>
<div class="row">
  <div class="col-sm-12">
    <br />
    <%= link_to "Create New Recipe", new_recipe_path(@recipe), class: "btn btn-success" %></p>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-sm-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef: <%= link_to recipe.chef.name, chef_path(recipe.chef) %></h5>
      </section>
    </div>
    
    <div class="col-sm-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <% if recipe.styles.any? %><p><small>Style: <%= render recipe.styles %></small></p><% end %>
      <% if recipe.ingredients.any? %><p><small>Ingredients: <%= render recipe.ingredients %></small></p><% end %>
      <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span></p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i><% end %> 
          <%= recipe.thumbs_up_total %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i><% end %> 
          <%= recipe.thumbs_down_total %>
      </div>
    </div>
    
    <div class="col-sm-4">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'New Recipe' %>
<%= render 'form' %>
<%= link_to 'Return to recipes listing without saving', recipes_path, class: "btn btn-warning" %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-sm-8">
    <h3><%= @recipe.summary %></h3>
    
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    
    <div class="well">
      <% if @recipe.styles.any? %><p><small>Style: <%= render @recipe.styles %></small></p><% end %>
      <% if @recipe.ingredients.any? %><p><small>Ingredients: <%= render @recipe.ingredients %></small></p><% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i><% end %> 
          <%= @recipe.thumbs_up_total %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i><% end %> 
          <%= @recipe.thumbs_down_total %>
      </div>
    </div>
  </div>
  
  <div class="col-sm-4 center">
    <%= link_to gravatar_for(@recipe.chef, size: 150), chef_path(@recipe.chef) %>
    <p>Brought to you by <%= link_to @recipe.chef.name, chef_path(@recipe.chef) %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-8">
    <%= link_to 'Return to recipes listing', recipes_path, class: "btn btn-warning" %>
    <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
      | <%= link_to 'Edit', edit_recipe_path(@recipe) %>
    <% end %>
    <% if logged_in? and current_user.admin? %>
      | <%= link_to '[Delete recipe]', @recipe, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
</div>