config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/home", to: "pages#home"
  
  #get "/recipes", to: "recipes#index"
  #get "/recipes/new", to: "recipes#new", as: "new_recipe"
  #post "/recipes", to: "recipes#create"
  #get "/recipes/:id/edit", to: "recipes#edit", as: "edit_recipe"
  #patch "/recipes/:id", to: "recipes#update"
  #get "/recipes/:id", to: "recipes#show", as: "recipe"
  #delete "/recipes/:id", to: "recipes#destroy"
  
  # rails generate the generic form described earlier
  resources :recipes, except: [:destroy] do
    member do
      post 'like'
    end
  end
  
  delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :chefs, except: [:new] do
    member do
      post 'like'
    end
  end
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [ :new, :create, :show ]
  resources :ingredients, only: [ :new, :create, :show ]
  
end

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to myRecipes platform</h1>
  <h2>This is the home page developed during the Professional Ruby on Rails Developer Course on Udemy.</h2>
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">View recipes as Guest User</h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p><%= link_to "Browse recipes listing", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">Sign in to your account</h3>
    <h2 class="left">Add, update, review, like or dislike recipes and much more!</h2>
    <p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">View recipes as Guest User</h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p><%= link_to "Browse recipes listing", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
</div>