config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/home", to: "pages#home"
  
  #get "/recipes", to: "recipes#index"
  #get "/recipes/new", to: "recipes#new", as: "new_recipe"
  #post "/recipes", to: "recipes#create"
  #get "/recipes/:id/edit", to: "recipes#edit", as: "edit_recipe"
  #patch "/recipes/:id", to: "recipes#update"
  #get "/recipes/:id", to: "recipes#show", as: "recipe"
  #delete "/recipes/:id", to: "recipes#destroy"
  
  # rails generate the generic form described earlier
  resources :recipes, except: [:destroy] do
    member do
      post 'like'
    end
  end
  
  delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :chefs, except: [:new] do
    member do
      post 'like'
    end
  end
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [ :new, :create, :show ]
  resources :ingredients, only: [ :new, :create, :show ]
  
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 40 }
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :require_user, except: [:show]
  
  def new
    @style = Style.new
  end
  
  def create
    @style = Style.new(style_params)
    
    if @style.save
      flash[:success] = "Style was created successfully!"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  def show
    @style = Style.find(params[:id])
    @recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
  end
  
  private
    def style_params
      params.require(:style).permit(:name)
    end
end

app/views/styles/_style.html.erb
<span class="quiet style"><%= link_to style.name, style_path(style) %></span> 

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: 'New Style' %>

<%= render "shared/errors", obj: @style %>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <%= form_for @style do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.submit "Create Style", class: "btn btn-success" %>
      </p>
    <% end %>
  </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: 'Recipes for: ' + @style.name + ' food' %>

<ul class="nav nav-tabs">
  <li class="active"><%= link_to "Recipes", recipes_path %></li>
  <li><%= link_to "Chefs", chefs_path %></li>
</ul>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4 center">
    <%= will_paginate @recipes %>
  </div>
</div>

<% @style.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-sm-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef: <%= link_to recipe.chef.name, chef_path(recipe.chef) %></h5>
      </section>
    </div>
    
    <div class="col-sm-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <% if recipe.styles.count > 0 %><p><small>Style: <%= render recipe.styles %></small></p><% end %>
      <% if recipe.ingredients.count > 0 %><p><small>Ingredients: <%= render recipe.ingredients %></small></p><% end %>
      <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span></p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i><% end %> 
          <%= recipe.thumbs_up_total %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i><% end %> 
          <%= recipe.thumbs_down_total %>
      </div>
    </div>
    
    <div class="col-sm-4">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4 center">
    <%= will_paginate @recipes %>
  </div>
</div>